[[repo]]
name = "family-film-scores"
[repo.config]
server = "Local"
builder = "Local"
git_account = "philjackson"
repo = "philjackson/family-film-scores"

##

[[build]]
name = "family-film-scores"
tags = ["media"]
[build.config]
builder = "Local"
linked_repo = "family-film-scores"

##

[[stack]]
name = "family-film-scores"
tags = ["media"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/family-film-scores"
file_paths = ["compose.yml"]

##

[[stack]]
name = "deezmix"
tags = ["music", "media"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/deezmix"
file_paths = ["compose.yml"]

##

[[stack]]
name = "gluetun-and-co"
tags = ["system", "media"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/gluetun-and-co"
file_paths = ["compose.yml"]

##

[[stack]]
name = "homeassistant"
tags = ["home"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/homeassistant"
file_paths = ["compose.yml"]

##

[[stack]]
name = "jellyfin"
tags = ["media"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/jellyfin"
file_paths = ["compose.yml"]

##

[[stack]]
name = "seerr"
tags = ["media"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/seerr"
file_paths = ["compose.yml"]

##

[[stack]]
name = "pihole"
tags = ["system"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/pihole"
file_paths = ["compose.yml"]

##

[[stack]]
name = "syncthing"
tags = ["system"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/syncthing"
file_paths = ["compose.yml"]

##

[[stack]]
name = "traefik"
tags = ["system"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/traefik"
file_paths = ["compose.yml"]

##

[[stack]]
name = "uptime-kuma"
tags = ["system"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/uptime-kuma"
file_paths = ["compose.yml"]

##

[[stack]]
name = "zigbee2mqtt"
tags = ["home"]
[stack.config]
server = "Local"
poll_for_updates = true
files_on_host = true
run_directory = "/home/pi/docker-compose-files/zigbee2mqtt"
file_paths = ["compose.yml"]
