###################################
# ðŸ¦Ž KOMODO COMPOSE - FERRETDB ðŸ¦Ž #
###################################

## This compose file will deploy:
##   1. Postgres + FerretDB Mongo adapter (https://www.ferretdb.com)
##   2. Komodo Core
##   3. Komodo Periphery

services:
  postgres:
    # https://github.com/FerretDB/documentdb/pkgs/container/postgres-documentdb
    image: ghcr.io/ferretdb/postgres-documentdb
    container_name: komodo-postgres
    restart: unless-stopped
    networks:
      - default
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    volumes:
      - /home/pi/apps/komodo/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${KOMODO_DB_USERNAME}
      POSTGRES_PASSWORD: ${KOMODO_DB_PASSWORD}
      POSTGRES_DB: postgres

  ferretdb:
    # https://github.com/FerretDB/FerretDB/pkgs/container/ferretdb
    image: ghcr.io/ferretdb/ferretdb
    container_name: komodo-ferretdb
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - default
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    volumes:
      - /home/pi/apps/komodo/ferretdb:/state
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@postgres:5432/postgres

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo
    restart: unless-stopped
    depends_on:
      - ferretdb
    networks:
      - default
      - traefik-net
    ports:
      - 9120:9120
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      traefik.enable: true
      traefik.docker.network: traefik-net
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: ferretdb:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - /home/pi/apps/komodo/backups:/backups
      - /home/pi/docker-compose-files:/syncs:ro
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-periphery
    restart: unless-stopped
    env_file: .env
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      - /home/pi/apps/komodo/periphery:/home/pi/apps/komodo/periphery
      ## Allow Periphery to access compose files on host
      - /home/pi/docker-compose-files:/home/pi/docker-compose-files

networks:
  traefik-net:
    external: true
