services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8989:8989/tcp # sonarr
      - 7878:7878/tcp # radarr
      - 8085:8085/tcp # qtorrent
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696     # prowlarr
    volumes:
      - /home/pi/apps/gluton:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=15mRTY8VzxXnsnoo
      - OPENVPN_PASSWORD=IZrgGGWd3nW4mIcoaAMvY0lDYT4TiHIk
      - UPDATER_PROTONVPN_USERNAME=15mRTY8VzxXnsnoo
      - UPDATER_PROTONVPN_PASSWORD=IZrgGGWd3nW4mIcoaAMvY0lDYT4TiHIk
      - TZ=Europe/London
      - SERVER_COUNTRIES=Netherlands,Switzerland
      - LOG_LEVEL=debug
    networks:
      - traefik-net

  qtorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qtorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8085
    volumes:
      - /home/pi/apps/qtorrent:/config
      - /home/pi/external/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qtorrent.loadbalancer.server.port=8085"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/apps/radarr:/config
      - /home/pi/external/live/Film:/data
      - /home/pi/external/downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/apps/sonarr:/config
      - /home/pi/external/live/Tv:/data
      - /home/pi/external/downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/apps/prowlarr:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

networks:
  traefik-net:
    external: true
