# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "81:80/tcp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      WEBPASSWORD: 'Tissue8-Envoy2-Acetone7-Puppy5-Juggling8'
      FTLCONF_webserver_api_password: 'Tissue8-Envoy2-Acetone7-Puppy5-Juggling8'
      # Wildcard DNS: resolves all *.home.lan to the server so Traefik can route them
      FTLCONF_misc_dnsmasq_lines: 'address=/home.lan/192.168.0.100'
    volumes:
      - '/home/pi/apps/pihole/etc/pihole:/etc/pihole'
      - '/home/pi/apps/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
    networks:
      traefik-net:
        ipv4_address: 172.30.0.53
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
